package com.tapeverify.copilot.controller;
import com.tapeverify.copilot.dto.*; import com.tapeverify.copilot.entity.*; import com.tapeverify.copilot.repository.*; import com.tapeverify.copilot.service.*; import java.nio.charset.StandardCharsets; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class VerificationController {
 private final VerificationService service; private final VerifiedLoanRepository verified; private final LoanRepository loans; private final LoanBatchRepository batches; private final AuditService audit; private final com.fasterxml.jackson.databind.ObjectMapper json;
 public VerificationController(VerificationService service,VerifiedLoanRepository verified,LoanRepository loans,LoanBatchRepository batches,AuditService audit,com.fasterxml.jackson.databind.ObjectMapper json){this.service=service;this.verified=verified;this.loans=loans;this.batches=batches;this.audit=audit;this.json=json;}
 @PostMapping("/loans/{id}/review") public Map<String,Object> review(@PathVariable Long id,@RequestBody ReviewActionDto dto){var v=service.decide(id,dto.getExceptionId(),dto.getAction(),dto.getComment());return v==null?Map.of("status","recorded"):Map.of("status","verified","verifiedId",v.getId());}
 @GetMapping("/loans/{id}/review-actions") public List<Map<String,Object>> actions(@PathVariable Long id){return service.actions(id);}
 @GetMapping("/verified-loans") public List<Map<String,Object>> list(){return verified.findAll().stream().map(this::dto).toList();}
 @GetMapping("/verified-loans/{id}") public Map<String,Object> one(@PathVariable Long id){return dto(verified.findById(id).orElseThrow(()->new IllegalArgumentException("Verified record not found")));}
 @GetMapping(value="/verified-loans/export",produces="text/csv") public ResponseEntity<byte[]> export(){List<VerifiedLoan> records=verified.findAll();String csv="verified_id,loan_id,source_loan_id,borrower,verified_by,verified_at\n"+records.stream().map(v->String.join(",",csv(v.getId()),csv(v.getLoan().getId()),csv(v.getLoan().getSourceLoanId()),csv(v.getLoan().getBorrowerName()),csv(v.getVerifiedBy()),csv(v.getVerifiedAt()))).collect(java.util.stream.Collectors.joining("\n"));String actor=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication().getName();records.forEach(v->audit.record(v.getLoan(),AuditAction.VERIFIED_RECORD_EXPORTED,actor,null,null));return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=verified-loans.csv").body(csv.getBytes(StandardCharsets.UTF_8));}
 @GetMapping("/summary") public Map<String,Object> summary(){long total=loans.count(), open=loans.countByStatus(LoanStatus.EXCEPTION), complete=loans.countByStatus(LoanStatus.VALID)+loans.countByStatus(LoanStatus.RESOLVED)+verified.count();double score=total==0?0:Math.round((complete*10000.0/total))/100.0;return Map.of("totalLoans",total,"totalBatches",batches.count(),"openExceptions",open,"verifiedLoans",verified.count(),"resolvedLoans",loans.countByStatus(LoanStatus.RESOLVED),"qualityScore",score);}
 private Map<String,Object> dto(VerifiedLoan v){Map<String,Object> x=new LinkedHashMap<>();x.put("id",v.getId());x.put("loanId",v.getLoan().getId());x.put("sourceLoanId",v.getLoan().getSourceLoanId());x.put("sourceFileId",v.getLoan().getSourceFileId());x.put("borrowerName",v.getLoan().getBorrowerName());x.put("verifiedBy",v.getVerifiedBy());x.put("verifiedAt",v.getVerifiedAt());x.put("decision",v.getDecision());x.put("validationResult","PASSED");x.put("recordHash",v.getRecordHash());x.put("aiRecommendationUsed",v.getLoan().getValidationExceptions().stream().anyMatch(e->e.getAiExplanation()!=null));try{x.put("canonicalLoan",json.readValue(v.getCanonicalDetails(),Object.class));}catch(Exception e){x.put("canonicalLoan",v.getCanonicalDetails());}return x;}
 private String csv(Object value){String text=value==null?"":value.toString();if(!text.isEmpty()&&"=+-@".indexOf(text.charAt(0))>=0)text="'"+text;return "\""+text.replace("\"","\"\"")+"\"";}
}
