package com.tapeverify.copilot.entity;
public enum AuditAction { FILE_UPLOADED, CREATED, VALIDATION_EXECUTED, EXCEPTION_CREATED, AI_RECOMMENDATION_GENERATED, REVIEWER_COMMENT, AI_FIX_APPLIED, MANUAL_OVERRIDE, LOAN_APPROVED, LOAN_REJECTED, VERIFIED_RECORD_CREATED, VERIFIED_RECORD_EXPORTED }
