spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    model:
      chat: openai
      embedding: none
      image: none
      audio:
        transcription: none
        speech: none
      moderation: none
