package com.tapeverify.copilot.service;

import com.fasterxml.jackson.databind.ObjectMapper; import com.tapeverify.copilot.dto.BatchSummaryDto; import com.tapeverify.copilot.entity.*; import com.tapeverify.copilot.exception.FileProcessingException; import com.tapeverify.copilot.repository.*; import com.tapeverify.copilot.util.*; import java.time.LocalDateTime; import java.util.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
@Service public class IngestionServiceImpl implements IngestionService {
 private final LoanRepository loans; private final LoanBatchRepository batches; private final UploadedSourceFileRepository files; private final ValidationService validation; private final AuditService audit; private final ObjectMapper json;
 public IngestionServiceImpl(LoanRepository loans,LoanBatchRepository batches,UploadedSourceFileRepository files,ValidationService validation,AuditService audit,ObjectMapper json){this.loans=loans;this.batches=batches;this.files=files;this.validation=validation;this.audit=audit;this.json=json;}
 @Transactional public BatchSummaryDto ingest(MultipartFile file){return ingest(file,"PRIMARY");}
 @Transactional public BatchSummaryDto ingest(MultipartFile file,String requestedType){if(file==null||file.isEmpty())throw new FileProcessingException("Upload a non-empty CSV file");if(file.getSize()>10*1024*1024||file.getOriginalFilename()==null||!file.getOriginalFilename().toLowerCase().endsWith(".csv"))throw new FileProcessingException("Upload a CSV file no larger than 10 MB");String type=Optional.ofNullable(requestedType).orElse("PRIMARY").trim().toUpperCase();if(!Set.of("PRIMARY","SERVICER_UPDATE","DOCUMENT_MANIFEST").contains(type))throw new FileProcessingException("Unsupported source type");String id=UUID.randomUUID().toString().replace("-","");String fileId=UUID.randomUUID().toString().replace("-","");String actor=SecurityContextHolder.getContext().getAuthentication().getName();try{byte[] content=file.getBytes();files.save(UploadedSourceFile.builder().id(fileId).originalFilename(file.getOriginalFilename()).contentType(file.getContentType()).sourceType(type).contentSha256(HashUtil.hashBytes(content)).uploadedBy(actor).uploadedAt(LocalDateTime.now()).fileContent(content).build());LoanBatch batch=LoanBatch.builder().id(id).sourceFileId(fileId).sourceType(type).sourceFilename(file.getOriginalFilename()).uploadedBy(actor).uploadedAt(LocalDateTime.now()).status("PROCESSING").build();batches.save(batch);int valid=0,exceptionRows=0,failed=0,total=0;for(CsvParserUtil.LoanRow row:CsvParserUtil.parse(new java.io.ByteArrayInputStream(content))){total++;if(!"PRIMARY".equals(type)){SupplementalResult supplemental=applySupplemental(row,type,fileId,actor);if(supplemental.matched()){if(supplemental.conflict())exceptionRows++;else valid++;continue;}}Loan loan=loan(id,fileId,row);var errors=validation.validate(loan);for(var p:row.parseIssues())errors.add(ValidationException.builder().loan(loan).fieldName(p.fieldName()).severity("HIGH").errorMessage(p.message()).rawValue(p.rawValue()).rowNumber(row.rowNumber()).resolved(false).build());for(var e:errors){e.setLoan(loan);if(e.getRowNumber()==null)e.setRowNumber(row.rowNumber());if(e.getRawValue()==null)e.setRawValue(row.rawValues().get(e.getFieldName()));}loan.setStatus(errors.isEmpty()?LoanStatus.VALID:LoanStatus.EXCEPTION);loan.setSha256Hash(HashUtil.hash(loan));loan.getValidationExceptions().addAll(errors);loans.save(loan);audit.record(loan,AuditAction.FILE_UPLOADED,actor,null,null);audit.record(loan,AuditAction.CREATED,actor,null,null);audit.record(loan,AuditAction.VALIDATION_EXECUTED,actor,null,null);for(int i=0;i<errors.size();i++)audit.record(loan,AuditAction.EXCEPTION_CREATED,actor,null,null);if(errors.isEmpty())valid++;else{exceptionRows++;if(!row.parseIssues().isEmpty())failed++;}}
 batch.setTotalRows(total);batch.setValidRows(valid);batch.setExceptionRows(exceptionRows);batch.setFailedRows(failed);batch.setStatus("COMPLETED");batches.save(batch);return summary(batch);}catch(FileProcessingException e){throw e;}catch(Exception e){throw new FileProcessingException("Unable to process the uploaded CSV",e);}}
 private Loan loan(String batchId,String fileId,CsvParserUtil.LoanRow r)throws Exception{return Loan.builder().batchId(batchId).sourceFileId(fileId).sourceLoanId(r.sourceLoanId()).sourceRowNumber(r.rowNumber()).rawValues(json.writeValueAsString(r.rawValues())).borrowerId(r.borrowerId()).borrowerName(r.borrowerName()).principalAmount(r.principalAmount()).currentBalance(r.currentBalance()).interestRate(r.interestRate()).originationDate(r.originationDate()).maturityDate(r.maturityDate()).paymentStatus(r.paymentStatus()).daysPastDue(r.daysPastDue()).borrowerState(r.borrowerState()).documentStatus(r.documentStatus()).lastUpdatedAt(r.lastUpdatedAt()).sourceSystem(r.sourceSystem()).loanType(r.loanType()).termMonths(r.termMonths()).loanPurpose(r.loanPurpose()).creditGrade(r.creditGrade()).employmentLength(r.employmentLength()).incomeBand(r.incomeBand()).lastPaymentDate(r.lastPaymentDate()).createdAt(LocalDateTime.now()).status(LoanStatus.PENDING).sha256Hash("").build();}
 private SupplementalResult applySupplemental(CsvParserUtil.LoanRow row,String type,String sourceFileId,String actor){if(row.sourceLoanId()==null||row.sourceLoanId().isBlank())return new SupplementalResult(false,false);List<Loan> matching=loans.findBySourceLoanId(row.sourceLoanId());if(matching.isEmpty())return new SupplementalResult(false,false);boolean foundConflict=false;for(Loan existing:matching){String old=existing.getSha256Hash();boolean conflict=false;if(row.currentBalance()!=null&&existing.getCurrentBalance()!=null&&row.currentBalance().compareTo(existing.getCurrentBalance())!=0)conflict|=conflict(existing,"currentBalance","Conflicting current balance from "+type,row.currentBalance().toPlainString(),row.rowNumber());if(row.paymentStatus()!=null&&existing.getPaymentStatus()!=null&&!row.paymentStatus().equalsIgnoreCase(existing.getPaymentStatus()))conflict|=conflict(existing,"paymentStatus","Conflicting payment status from "+type,row.paymentStatus(),row.rowNumber());if(row.documentStatus()!=null&&existing.getDocumentStatus()!=null&&!row.documentStatus().equalsIgnoreCase(existing.getDocumentStatus()))conflict|=conflict(existing,"documentStatus","Conflicting document status from "+type,row.documentStatus(),row.rowNumber());if(conflict){foundConflict=true;existing.setStatus(LoanStatus.EXCEPTION);existing.setSha256Hash(HashUtil.hash(existing));loans.save(existing);audit.record(existing,AuditAction.EXCEPTION_CREATED,actor,old,null);}}return new SupplementalResult(true,foundConflict);}
 private boolean conflict(Loan loan,String field,String message,String raw,int row){loan.getValidationExceptions().add(ValidationException.builder().loan(loan).fieldName(field).severity("HIGH").errorMessage(message).rawValue(raw).rowNumber(row).resolved(false).build());return true;}
 private record SupplementalResult(boolean matched,boolean conflict){}
 private BatchSummaryDto summary(LoanBatch b){return BatchSummaryDto.builder().batchId(b.getId()).sourceType(b.getSourceType()).filename(b.getSourceFilename()).uploadedBy(b.getUploadedBy()).uploadedAt(b.getUploadedAt()).status(b.getStatus()).totalRecords(b.getTotalRows()).validRecords(b.getValidRows()).exceptionRecords(b.getExceptionRows()).failedRecords(b.getFailedRows()).build();}
}
