package com.tapeverify.copilot.service;
import com.tapeverify.copilot.dto.*; import com.tapeverify.copilot.entity.*; import com.tapeverify.copilot.exception.LoanNotFoundException; import com.tapeverify.copilot.repository.*; import com.tapeverify.copilot.util.HashUtil; import java.util.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class LoanServiceImpl implements LoanService {
 private final LoanRepository loans; private final ValidationExceptionRepository exceptions; private final ValidationService validation; private final AuditService audit; public LoanServiceImpl(LoanRepository loans,ValidationExceptionRepository exceptions,ValidationService validation,AuditService audit){this.loans=loans;this.exceptions=exceptions;this.validation=validation;this.audit=audit;}
 public List<LoanDto> all(){return loans.findAll().stream().map(this::dto).toList();} public List<LoanDto> exceptions(){return loans.findByStatus(LoanStatus.EXCEPTION).stream().map(this::dto).toList();} public LoanDto find(Long id){return dto(get(id));}
 @Transactional public LoanDto resolve(Long id,ResolveDto u){Loan loan=get(id);String oldHash=loan.getSha256Hash();AuditLoanSnapshotDto oldDetails=AuditLoanSnapshotDto.from(loan);if(u.getBorrowerName()!=null)loan.setBorrowerName(u.getBorrowerName().trim());if(u.getPrincipalAmount()!=null)loan.setPrincipalAmount(u.getPrincipalAmount());if(u.getCurrentBalance()!=null)loan.setCurrentBalance(u.getCurrentBalance());if(u.getInterestRate()!=null)loan.setInterestRate(u.getInterestRate());if(u.getOriginationDate()!=null)loan.setOriginationDate(u.getOriginationDate());if(u.getMaturityDate()!=null)loan.setMaturityDate(u.getMaturityDate());if(u.getPaymentStatus()!=null)loan.setPaymentStatus(u.getPaymentStatus().trim().toUpperCase());if(u.getDaysPastDue()!=null)loan.setDaysPastDue(u.getDaysPastDue());if(u.getBorrowerState()!=null)loan.setBorrowerState(u.getBorrowerState().trim().toUpperCase());if(u.getDocumentStatus()!=null)loan.setDocumentStatus(u.getDocumentStatus().trim().toUpperCase());if(u.getLastUpdatedAt()!=null)loan.setLastUpdatedAt(u.getLastUpdatedAt());if(u.getSourceSystem()!=null)loan.setSourceSystem(u.getSourceSystem().trim());var errors=validation.validate(loan);if(!errors.isEmpty())throw new IllegalArgumentException(errors.stream().map(ValidationException::getErrorMessage).collect(java.util.stream.Collectors.joining("; ")));exceptions.findByLoanIdAndResolvedFalse(id).forEach(e->e.setResolved(true));loan.setStatus(LoanStatus.RESOLVED);loan.setSha256Hash(HashUtil.hash(loan));loans.save(loan);audit.record(loan,u.isApplyAiSuggestion()?AuditAction.AI_FIX_APPLIED:AuditAction.MANUAL_OVERRIDE,actor(),oldHash,oldDetails);return dto(loan);}
 private String actor(){return SecurityContextHolder.getContext().getAuthentication().getName();} private Loan get(Long id){return loans.findById(id).orElseThrow(()->new LoanNotFoundException(id));}
 private LoanDto dto(Loan l){return LoanDto.builder().id(l.getId()).batchId(l.getBatchId()).sourceFileId(l.getSourceFileId()).sourceLoanId(l.getSourceLoanId()).sourceRowNumber(l.getSourceRowNumber()).borrowerId(l.getBorrowerId()).borrowerName(l.getBorrowerName()).principalAmount(l.getPrincipalAmount()).currentBalance(l.getCurrentBalance()).interestRate(l.getInterestRate()).paymentStatus(l.getPaymentStatus()).daysPastDue(l.getDaysPastDue()).borrowerState(l.getBorrowerState()).documentStatus(l.getDocumentStatus()).lastUpdatedAt(l.getLastUpdatedAt()).sourceSystem(l.getSourceSystem()).loanType(l.getLoanType()).termMonths(l.getTermMonths()).loanPurpose(l.getLoanPurpose()).creditGrade(l.getCreditGrade()).employmentLength(l.getEmploymentLength()).incomeBand(l.getIncomeBand()).lastPaymentDate(l.getLastPaymentDate()).originationDate(l.getOriginationDate()).maturityDate(l.getMaturityDate()).status(l.getStatus()).exceptions(l.getValidationExceptions().stream().map(e->ExceptionDto.builder().id(e.getId()).fieldName(e.getFieldName()).errorMessage(e.getErrorMessage()).severity(e.getSeverity()).rowNumber(e.getRowNumber()).rawValue(e.getRawValue()).normalizedValue(e.getNormalizedValue()).aiExplanation(e.getAiExplanation()).aiSuggestedValue(e.getAiSuggestedValue()).aiConfidence(e.getAiConfidence()).aiReasoningSummary(e.getAiReasoningSummary()).resolved(e.isResolved()).build()).toList()).build();}
}
